#casual_cases.py
# This module contains a list of humorous and light-hearted legal cases that are not serious in nature
CASUAL_CASES = [
    "The defendant is accused of stealing 400 bagels from the bakery.",
    "The defendant ran an illegal midnight pancake stand.",
    "The defendant started a food fight in city hall.",
    "The defendant was caught sneaking into a zoo to pet a lion.",
    "The defendant allegedly turned a library into a rave venue after hours.",
    "The defendant is accused of impersonating a mall Santa... in July.",
    "The defendant allegedly hacked into a video game leaderboard.",
    "The defendant is charged with throwing glitter at a police officer.",
    "The defendant was caught hosting squirrel racing tournaments for money.",
    "The defendant allegedly replaced all cafeteria food with candy.",
    "The defendant is accused of creating fake parking tickets for fun.",
    "The defendant built a giant slingshot and launched pumpkins across town.",
    "The defendant tried to bribe a judge with tacos.",
    "The defendant illegally opened a petting zoo in their apartment.",
    "The defendant installed a disco ball and speakers in a courtroom.",
    "The defendant was caught training pigeons to steal coins.",
    "The defendant held a parade without a permit... for their cat.",
    "The defendant is accused of replacing office coffee with hot sauce.",
    "The defendant allegedly taught raccoons how to skateboard.",
    "The defendant challenged the mayor to a dance-off on city property.",
    "The defendant built a robot that challenges people to rap battles.",
    "The defendant was caught having a fake political campaign... for their dog.",
    "The defendant filled the city fountain with bubble bath and glitter.",
    "The defendant is accused of painting graffiti in ancient Latin.",
    "The defendant faked a crime scene to get out of work.",
    "The defendant replaced all traffic signs with memes.",
    "The defendant allegedly flooded a parking lot to 'make a beach.'",
    "The defendant is accused of setting up a fake toll booth for coins.",
    "The defendant was caught putting googly eyes on statues around town.",
    "The defendant dressed as a ghost to haunt the DMV.",
    "The defendant threw a surprise birthday party for a stranger at a bus stop.",
    "The defendant built a giant hamster wheel and rolled it down Main Street.",
    "The defendant tried to adopt a llama using a fake ID.",
    "The defendant made hundreds of fake Yelp reviews for every store in the mall.",
    "The defendant started a protest against Mondays... alone.",
    "The defendant set up a fake art gallery full of macaroni sculptures.",
    "The defendant filled their front yard with inflatable dinosaurs.",
    "The defendant replaced vending machine snacks with vegetables.",
    "The defendant started a rumor that the mayor is an alien.",
    "The defendant live-streamed a sleepover in a supermarket.",
    "The defendant dressed pigeons in costumes and entered them in a fashion show.",
    "The defendant was caught printing memes on city flyers.",
    "The defendant installed a fake elevator button labeled 'space floor.'",
    "The defendant held a fake trial for their lost sock.",
    "The defendant glued googly eyes to a courtroom portrait.",
    "The defendant hacked an e-reader to only show dad jokes.",
    "The defendant hosted a TikTok dance-off in a public restroom.",
    "The defendant tried to make jury duty a reality show.",
    "The defendant challenged the police to a hide-and-seek competition.",
    "The defendant invented a conspiracy theory involving sandwiches.",
    "The defendant tried to legally marry their video game avatar.",
    "The defendant replaced the judge’s gavel with a squeaky toy.",
]
